server:
  port: ${API_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DB:rinha}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}